### ISSUE TITLE
push current version to pypi

### ISSUE THREAD

**Issue by walchko** [RedKrieg/pysparklines#4]
Looking at the pypi version, you haven't updated since 2013, but your commits add some py3 fixes. Could you update the package on pypi?

File | Type | Py Version | Uploaded on | Size
-- | -- | -- | -- | --
pysparklines-0.9.tar.gz (md5) | Source |   | 2013-08-22 | 3KB

**Comment by RedKrieg** [comment]
The current version in git still has a problem with encoding output.  I haven't really had time to build a proper set of tests to assure myself that python 3 support is complete, so I don't want to release a new version with python 3 support listed.  I actually don't know for sure why [this encode](https://github.com/RedKrieg/pysparklines/blob/7efdc98f841a0003e138a93c4e27cd71a64e7062/sparkline/sparkline.py#L97) exists anymore, but I suspect it had something to do with piping output on the command line.

```
redkrieg@cortex-0:~/projects/pysparklines$ python -c 'import sparkline; print (sparkline.sparkify([1,2,3]).encode("utf-8", "ignore"))'
▁▅█
redkrieg@cortex-0:~/projects/pysparklines$ python3 -c 'import sparkline; print (sparkline.sparkify([1,2,3]).encode("utf-8", "ignore"))'
b'\xe2\x96\x81\xe2\x96\x85\xe2\x96\x88'
```

**Comment by walchko** [comment]
I understand :smile:
